(function initInputMap(global) {
  const ACTION = Object.freeze({
    MENU_UP: "menu_up",
    MENU_DOWN: "menu_down",
    MENU_CONFIRM: "menu_confirm",
    DIALOGUE_ADVANCE: "dialogue_advance",
    INTERACT: "interact",
    ATTACK_BASIC: "attack_basic",
    CAST_WIND: "cast_wind",
    CAST_LEAF: "cast_leaf",
    DODGE: "dodge",
    CRAFT_RECIPE_BOOK: "craft_recipe_book",
    CRAFT_POTION: "craft_potion",
    USE_POTION: "use_potion",
    CRAFT_JAR: "craft_jar",
    SWAP_HERO: "swap_hero",
    OPEN_MENU: "open_menu",
    OPEN_CHARACTER_MENU: "open_character_menu",
    OPEN_INVENTORY: "open_inventory",
    OPEN_WORLD_MAP: "open_world_map",
    OPEN_COLLECTION: "open_collection",
    OPEN_GACHA: "open_gacha",
    CLOSE_OR_BACK: "close_or_back",
    TOGGLE_FULLSCREEN: "toggle_fullscreen",
    NAV_LEFT: "nav_left",
    NAV_RIGHT: "nav_right",
    CHOOSE_OPTION_A: "choose_option_a",
    CHOOSE_OPTION_B: "choose_option_b",
    GACHA_SPIN_ONE: "gacha_spin_one",
    MENU_TAB_CHARACTERS: "menu_tab_characters",
    MENU_TAB_BACKPACK: "menu_tab_backpack",
    MENU_TAB_BOOK: "menu_tab_book",
    GACHA_CONFIRM: "gacha_confirm",
  });

  const ACTION_KEYS = Object.freeze({
    [ACTION.MENU_UP]: ["ArrowUp"],
    [ACTION.MENU_DOWN]: ["ArrowDown"],
    [ACTION.MENU_CONFIRM]: ["Enter"],
    [ACTION.DIALOGUE_ADVANCE]: ["Enter", "KeyE", "Space"],
    [ACTION.INTERACT]: ["KeyE", "Enter"],
    [ACTION.ATTACK_BASIC]: ["KeyJ", "KeyB"],
    [ACTION.CAST_WIND]: ["KeyK", "KeyA"],
    [ACTION.CAST_LEAF]: ["KeyL"],
    [ACTION.DODGE]: ["Space"],
    [ACTION.CRAFT_RECIPE_BOOK]: ["KeyR"],
    [ACTION.CRAFT_POTION]: ["KeyH"],
    [ACTION.USE_POTION]: ["KeyU"],
    [ACTION.CRAFT_JAR]: ["KeyY"],
    [ACTION.SWAP_HERO]: ["KeyT"],
    [ACTION.OPEN_MENU]: ["KeyM"],
    [ACTION.OPEN_CHARACTER_MENU]: ["KeyP"],
    [ACTION.OPEN_INVENTORY]: ["KeyI"],
    [ACTION.OPEN_WORLD_MAP]: ["Tab"],
    [ACTION.OPEN_COLLECTION]: ["KeyC"],
    [ACTION.OPEN_GACHA]: ["KeyG"],
    [ACTION.CLOSE_OR_BACK]: ["Escape"],
    [ACTION.TOGGLE_FULLSCREEN]: ["KeyF"],
    [ACTION.NAV_LEFT]: ["ArrowLeft", "KeyA"],
    [ACTION.NAV_RIGHT]: ["ArrowRight", "KeyD"],
    [ACTION.CHOOSE_OPTION_A]: ["KeyA", "KeyJ"],
    [ACTION.CHOOSE_OPTION_B]: ["KeyB", "KeyK", "Enter"],
    [ACTION.GACHA_SPIN_ONE]: ["KeyA", "KeyJ", "Enter"],
    [ACTION.MENU_TAB_CHARACTERS]: ["Digit1"],
    [ACTION.MENU_TAB_BACKPACK]: ["Digit2"],
    [ACTION.MENU_TAB_BOOK]: ["Digit3"],
    [ACTION.GACHA_CONFIRM]: ["Enter", "KeyE", "KeyO", "Space"],
  });

  global.ResonaInputMap = { ACTION, ACTION_KEYS };
})(window);
